config/routes.rb
Rails.application.routes.draw do
  # Back admin routes start
  namespace :admin do
    resources :users

    # Admin root
    root to: 'application#index'
  end
  # Back admin routes end

  # Front routes start
  devise_for :users, only: [:session, :registration], path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  # Application root
  root to: 'application#home'
  # Front routes end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_validator.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || 'is not a valid email')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  validates :name, presence: true
  validates :email, uniqueness: true, email: true

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    layout :layout_by_resource

    def index
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit(:password, :password_confirmation, :current_password, :name)
      end
    end

    private def layout_by_resource
      if devise_controller?
        'layouts/devise'
      else
        'admin/layouts/admin'
      end
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    respond_to :json, :html
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end

    # GET /users/1
    # GET /users/1.json
    def show
    end

    # GET /users/new
    def new
      @user = User.new
      @url = admin_users_path
    end

    # GET /users/1/edit
    def edit
      @url = admin_user_path(@user)
    end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)

      if @user.save
        flash[:notice] = t('admin.users.create.success')
        respond_with :edit, :admin, @user
      else
        flash[:warning] = @user.errors.full_messages.uniq.join(', ')
        respond_with :new, :admin, :user
      end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      if @user.update(user_params)
        flash[:notice] = t('admin.users.update.success')
        respond_with :edit, :admin, @user
      else
        flash[:warning] = @user.errors.full_messages.uniq.join(', ')
        respond_with :edit, :admin, :user
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to admin_users_path, notice: t('admin.users.destroy.success') }
        format.json { head :no_content }
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    private def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    private def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/index.html.erb
<div class="row">
  <div class="col-md-12">

    <div class="box box-info">
      <div class="box-header with-border">
        <h3 class="box-title"><%= t('admin.index.title') %></h3>
      </div>

      <div class="box-body"><%= t('admin.index.body') %></div>
    </div>

  </div>
</div>

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no, minimal-ui"/>
    <meta name="keywords" content="" />
    <meta name="title" content="<%= content_for?(:title) ? yield(:title) : Rails.application.secrets[:site_title] %>">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : Rails.application.secrets[:site_title] %>">
    <title><%= content_for?(:title) ? yield(:title) : Rails.application.secrets[:site_title] %></title>

    <%= stylesheet_link_tag 'application_back', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">

    <div class="wrapper">
      <%= render partial: 'admin/shared/header' %>
      <%= render partial: 'admin/shared/sidebar' %>
      <div class="content-wrapper">
        <%= render partial: 'admin/shared/content_header' %>
        <section class="content">
          <%= render partial: 'admin/shared/messages' %>
          <%= yield %>
        </section>
      </div>
      <%= render partial: 'admin/shared/footer' %>
    </div>
  </body>

  <%= javascript_include_tag 'application_back' %>

  <% if content_for?(:added_scripts) %>
    <%= yield :added_scripts %>
  <% end %>
</html>

app/views/admin/shared/_content_header.html.erb
<section class="content-header">
  <h1> <%= params[:controller].split('/').last.humanize %> </h1>
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-dashboard"></i> Home'.html_safe, admin_root_path %></li>
    <li class="active"> <%= params[:controller].split('/').last.humanize %> </li>
  </ol>
</section>

app/views/admin/shared/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 1.0.0
  </div>
  Made with ♥ by <a href="https://github.com/dreamingechoes">@dreamingechoes</a>.
</footer>

app/views/admin/shared/_header.html.erb
<header class="main-header">
  <%= content_tag :a, href: admin_root_path, class: 'logo' do %>
    <span class="logo-mini">
    <b>A</b>T</span>
    <span class="logo-lg">
    <b>AdminLTE</b>Template</span>
  <% end %>

  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag "http://placehold.it/160x160", class: "user-image" %>
            <span class="hidden-xs"><%= current_user.name %></span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-header">
              <%= image_tag "http://placehold.it/160x160", class: "img-circle" %>

              <p>
                <%= current_user.name %>
                <small>Member since <%= current_user.created_at.strftime("%B, %Y") %></small>
              </p>
            </li>

            <li class="user-footer">
              <div class="pull-left">
                <%= link_to 'Profile', edit_admin_user_path(current_user), class: 'btn btn-default -btn-flat' %>
              </div>
              <div class="pull-right">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat' %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/admin/shared/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h4>
        <i class="icon fa fa-<%= name.to_s == 'notice' ? 'check' : 'ban' %>"></i> 
        <%= name.to_s == 'notice' ? 'Success!' : 'Alert!' %>
      </h4>
      <%= content_tag :div, raw(msg.split(",").join("<br>").html_safe), :id => "flash_#{name}" %>
    </div>
    <% flash[name] = nil %>
  <% end %>
<% end %>

app/views/admin/shared/_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">

    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag "http://placehold.it/160x160", class: "img-circle" %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.name %></p>
        <%= link_to '<i class="fa fa-circle text-success"></i><span>Online</span>'.html_safe, admin_root_path %>
      </div>
    </div>

    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
          <button type="submit" name="search" id="search-btn" class="btn btn-flat">
            <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    </form>

    <ul class="sidebar-menu">
      <li class="header"><%= t('admin.sidebar.main_navigation') %></li>
      <li> <%= link_to '<i class="fa fa-dashboard"></i><span>Dashboard</span>'.html_safe, admin_root_path %> </li>

      <li class="header"><%= t('admin.sidebar.administration') %></li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-users"></i>
          <span>Users</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li> <%= link_to '<i class="fa fa-circle-o"></i> List Users'.html_safe, admin_users_path %> </li>
          <li> <%= link_to '<i class="fa fa-circle-o"></i> Create User'.html_safe, new_admin_user_path %> </li>
        </ul>
      </li>

    </ul>

  </section>
</aside>

app/views/admin/users/_form.html.erb
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control", placeholder: "Enter email", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control", placeholder: "Enter password", required: (@user.new_record? ? true : false) %>
  <span class="help-block"><i>* This field is required (leave blank if you are editing and don't want to change the password)</i><span>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password", required: (@user.new_record? ? true : false) %>
  <span class="help-block"><i>* This field is required (leave blank if you are editing and don't want to change the password)</i><span>
</div>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", placeholder: "Enter name", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

app/views/admin/users/edit.html.erb
<%= form_for @user, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">Edit User</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'admin/users/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancel', admin_users_path, class: 'btn btn-danger' %>
          <%= f.submit 'Submit', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">List of Users</h3>
        </div>

        <div class="box-body">
          <div id="user_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

            <div class="row">
              <div class="col-sm-12">
                <table id="user_index" class="table table-bordered table-striped dataTable" role="grid">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Email</th>
                      <th class="col-xs-1">Actions</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @users.each do |user| %>
                      <tr>
                        <td> <%= user.name %> </td>
                        <td> <%= user.email %> </td>
                        <td>
                          <div class="btn-row">
                            <%= link_to raw('<i class="fa fa-cogs"></i>'), edit_admin_user_url(user), class: 'btn btn-sm btn-warning' %>
                            <%= link_to raw('<i class="fa fa-trash"></i>'), admin_user_url(user), class: 'btn btn-sm btn-danger', method: :delete,
                                            data: { confirm: 'Are you sure you want to delete this element?' } %>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>

                  <tfoot>
                    <tr role="row">
                      <th>Name</th>
                      <th>Email</th>
                      <th class="col-xs-1">Actions</th>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-2 col-md-offset-10">
    <%= link_to 'New User', new_admin_user_path, class: 'btn btn-success pull-right' %>
  </div>
</div>

app/views/admin/users/new.html.erb
<%= form_for @user, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header">
          <h3 class="box-title">New User</h3>
        </div>

        <div class="box-body">
          <%= render partial: 'admin/users/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancel', admin_users_path, class: 'btn btn-danger' %>
          <%= f.submit 'Submit', class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/application/home.html.erb
<div class="inner cover">
  <h1 class="cover-heading"><%= t('home.title') %></h1>
  <p class="lead"><%= t('home.subtitle').html_safe %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no, minimal-ui"/>
    <meta name="keywords" content="" />
    <meta name="title" content="<%= content_for?(:title) ? yield(:title) : Rails.application.secrets[:site_title] %>">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : Rails.application.secrets[:site_title] %>">
    <title><%= content_for?(:title) ? yield(:title) : Rails.application.secrets[:site_title] %></title>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <%= render partial: 'shared/navigation' %>
          <%= yield %>
          <%= render partial: 'shared/footer' %>
        </div>
      </div>
    </div>

  </body>

  <%= javascript_include_tag 'application' %>

  <% if content_for?(:added_scripts) %>
    <%= yield :added_scripts %>
  <% end %>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no, minimal-ui"/>
    <meta name="keywords" content="" />
    <meta name="title" content="<%= content_for?(:title) ? yield(:title) : Rails.application.secrets[:site_title] %>">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : Rails.application.secrets[:site_title] %>">
    <title><%= content_for?(:title) ? yield(:title) : Rails.application.secrets[:site_title] %></title>

    <%= stylesheet_link_tag 'application_back', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body class="hold-transition login-page">

    <div class="login-box">
      <%= render partial: 'admin/shared/messages' %>
      <div class="login-logo">
        <a href="#"><b>AdminLTE</b>Template</a>
      </div>

      <div class="login-box-body">
        <%= yield %>
      </div>
    </div>

  <%= javascript_include_tag 'application_back' %>

  <% if content_for?(:added_scripts) %>
    <%= yield :added_scripts %>
  <% end %>
</html>

app/views/shared/_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p>Made with ♥ by <a href="https://github.com/dreamingechoes">@dreamingechoes</a>.</p>
  </div>
</div>

app/views/shared/_navigation.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand"><%= t('navigation.main_title') %></h3>
    <nav>
      <ul class="nav masthead-nav">
        <li> <%= link_to t('navigation.root'), root_path %> </li>
        <li> <%= link_to t('navigation.admin'), admin_root_path %> </li>
      </ul>
    </nav>
  </div>
</div>